# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/ubuntu/canonical/anbox-cloud-terraform/.terragrunt-local-state/stacks/infrastructure/.terragrunt-stack/juju_bootstrap/terraform.tfstate"
  }
}
