# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/ubuntu/canonical/anbox-cloud-terraform/.terragrunt-local-state/units/juju_bootstrap/terraform.tfstate"
  }
}
